# Generated by Django 3.2.4 on 2021-06-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0004_auto_20210609_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participant',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(null=True, to='accs.Student'),
        ),
    ]
