# Generated by Django 3.2.4 on 2021-06-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0005_auto_20210609_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='accs.Student'),
        ),
    ]
