# Generated by Django 3.2.4 on 2021-06-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0009_auto_20210610_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
