# Generated by Django 3.2.4 on 2021-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0010_event_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
